server:
  port: 8083

rest-config:
  moodleUrl: "http://localhost:8080/webservice/rest/server.php?wstoken=ef5a928918417e5b5627515576f95d12&moodlewsrestformat=json&wsfunction="
  universityUrl: "http://localhost:8000/castlemock/mock/rest/project/S7TYew/application/zr0GGE"

university-endpoints:
  syncGrades: "/actualizar"


#Format "Seconds Minuts Hours Days(* = Any day) Months(* = Any month) Day_of_the_week(? = Any day)"
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/db?allowPublicKeyRetrieval=true&useSSL=false
    username: "root"
    password: "password"
    spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  task:
    scheduling:
      cron: "10 51 12 * * ?"  # 6:00 AM todos los días
      zone: "America/Bogota"